### ISSUE TITLE
DESI and PhotoZ are not appearing on the Galaxy instance?

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/tools-astro#145]
@dsavchenko could you please check? At least DESI should be simple.

**Comment by dsavchenko** [comment]
It's a cluster-wide issue that affects the bot...

**Comment by dsavchenko** [comment]
DESI is affected by https://github.com/oda-hub/nb2workflow/issues/208

**Comment by dsavchenko** [comment]
PhotoZ requires `astrorama` conda channel, but we only use `conda-forge` in Galaxy

**Comment by volodymyrss** [comment]
> PhotoZ requires `astrorama` conda channel, but we only use `conda-forge` in Galaxy

On private instance, you can add `astrorama`, right?

**Comment by dsavchenko** [comment]
> On private instance, you can add `astrorama`, right?

Yes, right. I can add it if really needed

**Comment by volodymyrss** [comment]
> > On private instance, you can add `astrorama`, right?
> 
> Yes, right. I can add it if really needed

Please do, to test. Then maybe we migrate to conda-forge.

**Comment by dsavchenko** [comment]
> DESI is affected by [oda-hub/nb2workflow#208](https://github.com/oda-hub/nb2workflow/issues/208)

But see [comment](https://github.com/oda-hub/nb2workflow/issues/208#issuecomment-2471051228) there. It looks like DESI can't be easily added to Galaxy because it needs custom astroquery.

**Comment by volodymyrss** [comment]
> > DESI is affected by [oda-hub/nb2workflow#208](https://github.com/oda-hub/nb2workflow/issues/208)
> 
> But see [comment](https://github.com/oda-hub/nb2workflow/issues/208#issuecomment-2471051228) there. It looks like DESI can't be easily added to Galaxy because it needs custom astroquery.

@Andrei-EPFL , could you change to code of the notebook so that it does not depend on custom astroquery? Just take out the code from within custom astroquery module.

**Comment by dsavchenko** [comment]
> Please do, to test.

Well, I've just realised, the main issue with PhotoZ is PhosphorosTable input type. It's not yet supported and requires dedicated development

**Comment by volodymyrss** [comment]
> > Please do, to test.
> 
> Well, I've just realised, the main issue with PhotoZ is PhosphorosTable input type. It's not yet supported and requires dedicated development

Can you treat it as json-encoded string field? This should be a fallback for all parameters derived from StructuredParameter . I imagine some development to treat it as string, but not nearly as extensive specialized as that in MMODA.

**Comment by Andrei-EPFL** [comment]
I have adapted the environment.yml and added a "package" desi.py file in order to replace the github code. In addition, I have also added a galaxy_help.md file in the repository https://gitlab.renkulab.io/astronomy/mmoda/desi-legacy-survey . what would be the next step to make it go on galaxy?

**Comment by dsavchenko** [comment]
> what would be the next step to make it go on galaxy?

We need to merge https://github.com/oda-hub/nb2workflow/pull/209 first

**Comment by dsavchenko** [comment]
DESI is [there](https://github.com/esg-epfl-apc/tools-astro/pull/146)

PhotoZ needs https://github.com/oda-hub/oda-bot/issues/80

**Comment by Andrei-EPFL** [comment]
@dsavchenko is there something I have to do to get Photo-z on Galaxy?

**Comment by dsavchenko** [comment]
> is there something I have to do to get Photo-z on Galaxy?

I have to finish https://github.com/oda-hub/nb2workflow/pull/215 first

**Comment by dsavchenko** [comment]
This is fixed. Please complain and reopen if I miss something
