### ISSUE TITLE
Why two live previews with the same PR number?

### ISSUE THREAD

**Issue by dsavchenko** [esg-epfl-apc/tools-astro#147]
https://galaxy.odahub.fr/?tool_id=analyse_short_astro_text_astro_tool_pr146&version=latest
https://galaxy.odahub.fr/?tool_id=desi_legacy_survey_astro_tool_pr146&version=latest

**Comment by dsavchenko** [comment]
Will reopen if it repeats

**Comment by dsavchenko** [comment]
It's there once again

**Comment by Andrei-EPFL** [comment]
Thanks!

**Comment by dsavchenko** [comment]
So there were some files in `analyse_short_astro_texts` folder in DESI PR, maybe due to an old bug in the bot. Manually cleaned
