### ISSUE TITLE
newest pull request for analyse-short-text gives module not found (for a given .py file)

### ISSUE THREAD

**Issue by Andrei-EPFL** [esg-epfl-apc/tools-astro#150]
I have put inside the galaxy_help.md "*.py", but once I run the code in galaxy , it complains  "ModuleNotFoundError: No module named 'pipeline_astrobert'"

I am not sure whether something else has to be done.

also the newest pull request of analyse-short-text has the same number as for desi.
thanks!

**Comment by dsavchenko** [comment]
It wasn't actually updated, due to an issue. I included a hotfix in https://github.com/oda-hub/oda-bot/pull/82 that should resolve this.

**Comment by Andrei-EPFL** [comment]
Thanks @dsavchenko ! Now it has another issue, one that we saw already in the past:
FileNotFoundError: [Errno 2] No such file or directory: '/data/jobs/001/1391/data/telescope_observatory_survey.ttl'
@volodymyrss, I remember that we changed something

**Comment by dsavchenko** [comment]
> I remember that we changed something

I think you are talking about https://github.com/esg-epfl-apc/tools-astro/pull/113/commits/03e676e466f7e2554f3a3f77f99655b93bc471d5

Try to add this kind of workaround in your nb.

PS: It should be a proper Galaxy way to include data, but I didn't manage to do it properly yet

**Comment by Andrei-EPFL** [comment]
thanks @dsavchenko I managed to make it work now. I suppose I can close this issue and once you configure it properly I can change the repository.
