### ISSUE TITLE
new error on galaxy  for both desi and analyse-short-text, after fixing the astropy and oda-api versions

### ISSUE THREAD

**Issue by Andrei-EPFL** [esg-epfl-apc/tools-astro#153]
Failed to execute command-line /srv/galaxy/var/dependencies/_conda/bin/conda info --json, stderr was:
-------->>begin stderr<<--------

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/srv/g
      
      
Could you help me with this, please?

**Comment by Andrei-EPFL** [comment]
@dsavchenko I checked other tools (CTA, GRB-detection) and I get the same error. Thus, I suppose it is a problem of Galaxy.

**Comment by dsavchenko** [comment]
It was actually an issue in the installation of miniconda, libraries incompatibility occurred in the base environment during update. It's fixed now.
