### ISSUE TITLE
some tool comments

### ISSUE THREAD

**Issue by bgruening** [esg-epfl-apc/tools-astro#2]
## general

* drop python_template_version from the tool tag
* the fits datatype needs to be added to the Galaxy code base

## tool comments

* https://github.com/esg-epfl-apc/contributed-galaxy-workflows/blob/main/gammapysim/gammapysim.xml#L6
  * you can use `configfile` https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-configfiles-configfile 
* https://github.com/esg-epfl-apc/contributed-galaxy-workflows/blob/main/gammapy/gammapy.xml#L15
  * this config file should go into test-data dir
* https://github.com/esg-epfl-apc/contributed-galaxy-workflows/blob/main/astropytools/fitsinfo.xml#L38
  * use type="doi" here

**Comment by bgruening** [comment]
* https://github.com/esg-epfl-apc/contributed-galaxy-workflows/blob/main/odarequest.xml#L9

type string does not exist. It's `text` I guess. Are you using planemo.readthedocs.io to lint or test your tools?

**Comment by volodymyrss** [comment]
> drop python_template_version from the tool tag

Removed https://github.com/esg-epfl-apc/contributed-galaxy-workflows/commit/36767f969765ddeb0017bccd5c6971e5da81c3d1

**Comment by volodymyrss** [comment]
> the fits datatype needs to be added to the Galaxy code base

This is the most common astrophysical type, so this sounds certainly useful. How do we proceed to do that, @bgruening ?

**Comment by volodymyrss** [comment]
> * https://github.com/esg-epfl-apc/contributed-galaxy-workflows/blob/main/odarequest.xml#L9
> 
> 
> type string does not exist. It's `text` I guess. Are you using planemo.readthedocs.io to lint or test your tools?

Yes, but this is not one of the tools I want to add now and so it is not linted/tested.

**Comment by volodymyrss** [comment]
>     * https://github.com/esg-epfl-apc/contributed-galaxy-workflows/blob/main/astropytools/fitsinfo.xml#L38       
>       * use type="doi" here

changed https://github.com/esg-epfl-apc/contributed-galaxy-workflows/commit/f1cb3b1286dd30aa9bcaa9a48f8bfd37caf391f0

**Comment by volodymyrss** [comment]
> > the fits datatype needs to be added to the Galaxy code base
> 
> This is the most common astrophysical type, so this sounds certainly useful. How do we proceed to do that, @bgruening ?

should we follow https://docs.galaxyproject.org/en/latest/dev/data_types.html#data-types ?

**Comment by volodymyrss** [comment]
it produces something but I think maybe there was a way to visualize inside, but I am perplexed it did not recognize png.

![image](https://user-images.githubusercontent.com/3909535/230131381-419f79d5-6c70-4876-8d99-c15dda5f6bba.png)

**Comment by volodymyrss** [comment]
forcing format does it. I think this is even sort of useful basic tool which makes a viewable png image from fits file.

![image](https://user-images.githubusercontent.com/3909535/230160992-a5932a75-99b6-4f2e-9557-01eabacfb980.png)

Please provide more comments @bgruening  if any!

**Comment by bgruening** [comment]
> > the fits datatype needs to be added to the Galaxy code base
> 
> This is the most common astrophysical type, so this sounds certainly useful. How do we proceed to do that, @bgruening ?

Like here: https://github.com/galaxyproject/galaxy/pull/14504/ add it to Galaxy. The advanced option, as in the example PR, is to add a sniffing function to it as well. So Galaxy can extract some metadata.

**Comment by bgruening** [comment]
A tool needs to define the output filetype. There are ways around it by auto-detecting the format of an output, but we encourage people to set it explicitly. Based on the format, Galaxy can then offer some Vis or other tools to work on outputs. As seen here: https://github.com/galaxyproject/galaxy/pull/15394

**Comment by bgruening** [comment]
https://github.com/esg-epfl-apc/contributed-galaxy-workflows/tree/main/astropytools this folder looks very nice already. I would polish the help a bit but its a great first start. What you are missing is a ".shed.yml" file that contains the metadata for the Appstore. Take inspiration here: https://github.com/galaxyproject/tools-iuc/blob/main/tools/arriba/.shed.yml

The next step would be to add some CI/CD to this repo, or to you want to push those tools to other already existing tool repos?

This repo name is called "contributed-galaxy-workflows" but included are actually tools at the moment. Have a look how those repos can look like here: https://github.com/galaxyproject/tools-iuc

**Comment by volodymyrss** [comment]
> > > the fits datatype needs to be added to the Galaxy code base
> > 
> > 
> > This is the most common astrophysical type, so this sounds certainly useful. How do we proceed to do that, @bgruening ?
> 
> Like here: [galaxyproject/galaxy#14504](https://github.com/galaxyproject/galaxy/pull/14504) add it to Galaxy. The advanced option, as in the example PR, is to add a sniffing function to it as well. So Galaxy can extract some metadata.

Thanks, I will do it here https://github.com/galaxyproject/galaxy/pull/15905

**Comment by bgruening** [comment]
Cool, feel free to ping me when you are ready.

**Comment by volodymyrss** [comment]
- [ ] use configfile https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-configfiles-configfile
- [ ] config file should go into test-data dir
- [ ] use type="doi"
- [ ] drop python_template_version from the tool tag
- [ ] the fits datatype needs to be added to the Galaxy code base
- [ ] A tool needs to define the output filetype
- [ ] missing a ".shed.yml"
- [ ] add some CI/CD to this repo
- [ ] repo name is called "contributed-galaxy-workflows" but included are actually tools at the moment

**Comment by volodymyrss** [comment]
We had some issue that the tool (fitsinfo) added and tested with planemo in this repo was not working in an example deployment of @francoismg because "fitsinfo command not found" - i.e. the conda environment is somehow not completely initialized. Please @francoismg add more details as needed.

**Comment by francoismg** [comment]
> We had some issue that the tool (fitsinfo) added and tested with planemo in this repo was not working in an example deployment of @francoismg because "fitsinfo command not found" - i.e. the conda environment is somehow not completely initialized. Please @francoismg add more details as needed.

I tried to run "planemo test" again against that specific local galaxy instance just to be sure and it says that the tool passes the test but when you run the tool from the interface it outputs : 

`/tool_script.sh: line 10: fitsinfo: command not found`

It also passes the test when telling planemo to build a galaxy instance from scratch for testing the tool.

I replaced the out format that was causing some error to be sure that it wasn't linked (it clears the format error but not the command not found one)

However when running the test with --summary=compact the test still pass but there's that output after :

`command: *failed to find job for test object [{'id': 'fitsinfo (Test #1)', 'has_data': True, 'data': {'tool_id': 'fitsinfo', 'tool_version': '0.1.0+galaxy0', 'test_index': 0, 'time_seconds': 12.109392166137695, 'inputs': {'input1': {'src': 'hda', 'id': '8dc2150cd7713427'}}, 'job': {'model_class': 'Job', 'id': '8dc0fc122fa7705d', 'state': 'ok', 'exit_code': 0, 'update_time': '2023-05-08T12:16:16.067112', 'create_time': '2023-05-08T12:16:11.057043', 'galaxy_version': '23.1', 'command_version': '', 'tool_id': 'fitsinfo', 'history_id': '8dc2150cd7713427', 'external_id': '38675', 'command_line': "fitsinfo '/private/var/folders/ww/y9nt92_12tqdnz_2cwpwd9740000gn/T/tmp7evm84jp/files/d/5/e/dataset_d5e98a83-b408-499e-86a4-3fd7a3d1b8af.dat' | grep -vi filename > '/private/var/folders/ww/y9nt92_12tqdnz_2cwpwd9740000gn/T/tmp7evm84jp/job_working_directory/000/2/outputs/galaxy_dataset_5295f898-1943-4a03-b9e8-e1c1ce1ffb95.dat'", 'traceback': None, 'params': {'chromInfo': '"/Users/francoismg/galaxyproject/galaxy/tool-data/shared/ucsc/chrom/?.len"', 'dbkey': '"?"', '__input_ext': '"input"'}, 'inputs': {'input1': {'id': '8dc2150cd7713427', 'src': 'hda', 'uuid': 'd5e98a83-b408-499e-86a4-3fd7a3d1b8af'}}, 'outputs': {'output1': {'id': '8dc0fc122fa7705d', 'src': 'hda', 'uuid': '5295f898-1943-4a03-b9e8-e1c1ce1ffb95'}}, 'output_collections': {}, 'tool_stdout': '', 'tool_stderr': '', 'job_stdout': '', 'job_stderr': '', 'stderr': '', 'stdout': '', 'job_messages': [], 'dependencies': [], 'user_email': 'planemo@galaxyproject.org', 'job_metrics': []}, 'status': 'success'}}]`

Maybe it's just some noise but it might indicate that it can't test the tool with a specific job and so the command part is  never tested and only the lint test are executed

**Comment by bgruening** [comment]
I do not see version 5.1 here: https://anaconda.org/conda-forge/astropy/files?page=1

Can you use ?

```
<requirements>
        <requirement type="package" version="5.2.2">astropy</requirement>
 </requirements>

**Comment by volodymyrss** [comment]
> I do not see version 5.1 here: https://anaconda.org/conda-forge/astropy/files?page=1

here https://anaconda.org/conda-forge/astropy/files?version=5.1&page=1 ?
 
> Can you use ?
> 
> ```
> <requirements>
>         <requirement type="package" version="5.2.2">astropy</requirement>
>  </requirements>
> ```

There is no significant differences in these versions for our purposes here. It is, however, released every couple of month. So if we want a recent version all the time, we'll need to update it often.

**Comment by bgruening** [comment]
Oh I see, ok then I do not know why your installation of conda is failing. Can you share the tool - I will run it locally.

**Comment by volodymyrss** [comment]
> Oh I see, ok then I do not know why your installation of conda is failing. Can you share the tool - I will run it locally.

It's in here https://github.com/esg-epfl-apc/tools-astro/blob/main/tools/astropytools/fitsinfo.xml

It did work in my case at some point, like [here](https://github.com/esg-epfl-apc/tools-astro/issues/2#issuecomment-1497880287). I am not sure what's breaking for @francoismg , but it might break for other people.

**Comment by volodymyrss** [comment]
> https://github.com/esg-epfl-apc/contributed-galaxy-workflows/tree/main/astropytools this folder looks very nice already. I would polish the help a bit but its a great first start

As the [FITS format PR](https://github.com/galaxyproject/galaxy/pull/15905) is done, and [FITS visualization](https://github.com/galaxyproject/galaxy/pull/16187) looks good to us on the matter of features but needs review, should we publish [these tools](https://github.com/esg-epfl-apc/contributed-galaxy-workflows/tree/main/astropytools), in the toolshed, this is the way, @bgruening ?

**Comment by bgruening** [comment]
@volodymyrss I added a PR with a few comments https://github.com/esg-epfl-apc/tools-astro/pull/5/

I think they are ready to hit the TS. My comments are UX only, but would be nice if you could work on them. Thanks.
