### ISSUE TITLE
conesearch integration

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/tools-astro#36]
* integrate conesearch into the base adql query builder
* select box for two modes: by name and by coordinates
  * write formats for coordinate
  * radius should be right after the coordinate
* rename target field to observation target
* rename "search registry" to find all available archives
* may need to add timeout for some archives, maybe multithread

**Comment by volodymyrss** [comment]
is this done, @francoismg ?

**Comment by francoismg** [comment]
> is this done, @francoismg ?

Yes all good for conesearch, https://github.com/esg-epfl-apc/tools-astro/pull/40

There might be a possibility to add conesearch to other query builders than the IVOA one by letting the user choose which fields should be used for ra and dec, but it could be listed in a new issue if you think that feature might be useful

**Comment by volodymyrss** [comment]
Ok, thanks! Let's keep in mind.
