### ISSUE TITLE
tool id sometimes not gets changed in CI

### ISSUE THREAD

**Issue by dsavchenko** [esg-epfl-apc/tools-astro#58]
probably regex needs to be improved

ex: https://github.com/esg-epfl-apc/tools-astro/pull/56

**Comment by dsavchenko** [comment]
The reason is that id there contains a dash, requires changes to generator https://github.com/oda-hub/nb2workflow/issues/130

But name is arbitrary, so `regex_escape` filter should be used on it

**Comment by bgruening** [comment]
To avoid those problems with different version we recommend our users to use https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#tool-versions ... this helps our bot a lot :)

**Comment by dsavchenko** [comment]
> To avoid those problems with different version we recommend our users to use https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#tool-versions ... this helps our bot a lot :)

The intention here was to allow two versions of the same tool to coincide on the same staging server, so that we can have the "production" version installed from the toolshed and the "preview" from the PR installed directly. 
I thought for some reason that there is not possible to have two versions of the same tool installed, but if I'm wrong, there is no need to bother with this hack (probably still adding the PR number to the name for visual distinction).
